/**
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 **/
        
/**
 * This file was automatically generated by the Mule Development Kit
 */
package com.ricston.cassandradb.cql;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import org.junit.Test;
import org.mule.tck.junit4.FunctionalTestCase;

public class CassandraDbCqlConnectorTest extends FunctionalTestCase
{
	@Override
    protected String getConfigFile()
    {
        return "mule-config.xml";
    }

    @Test
    public void testFlow() throws Exception
    {
    	Map<String, Object> payload = new HashMap<String, Object>();
    	payload.put("id", UUID.fromString("f3d61f0a-95a9-4e24-a7cb-41ee19bf2355"));
    	payload.put("name", "name surname");
    	
    	runFlow("testFlow", payload);
    }

}
