CREATE TABLE testTable(
    id UUID PRIMARY KEY,
    value varchar,
);

INSERT INTO testTable(id, value) values(65b09341-cfc5-4ec6-a778-b6b5eabc61f1,'value001');
INSERT INTO testTable(id, value) values(65b09341-cfc5-4ec6-a778-b6b5eabc61f2,'value002');
INSERT INTO testTable(id, value) values(65b09341-cfc5-4ec6-a778-b6b5eabc61f3,'value003');
INSERT INTO testTable(id, value) values(65b09341-cfc5-4ec6-a778-b6b5eabc61f4,'value004');
INSERT INTO testTable(id, value) values(65b09341-cfc5-4ec6-a778-b6b5eabc61f5,'value005');
